import type { ShopItem } from './types.ts'

export const items: ShopItem[] = [
  {
    id: 'cinder-rounds',
    name: 'Cinder Rounds',
    category: 'Weapon',
    tier: 'TIER 1',
    cost: 900,
    tags: ['lane', 'cheap'],
    accent: '#fb7185',
    icon: 'bolt',
  },
  {
    id: 'signal-burner',
    name: 'Signal Burner',
    category: 'Weapon',
    tier: 'TIER 1',
    cost: 800,
    tags: ['starter', 'flex'],
    accent: '#f8a51c',
    icon: 'wave',
  },
  {
    id: 'storm-coil',
    name: 'Storm Coil',
    category: 'Weapon',
    tier: 'TIER 2',
    cost: 2400,
    tags: ['burst', 'precision'],
    accent: '#f97316',
    icon: 'blade',
  },
  {
    id: 'night-thread',
    name: 'Night Thread',
    category: 'Weapon',
    tier: 'TIER 3',
    cost: 4500,
    tags: ['finisher', 'burst'],
    accent: '#f43f5e',
    icon: 'blade',
  },
  {
    id: 'veil-amulet',
    name: 'Veil Amulet',
    category: 'Spirit',
    tier: 'TIER 1',
    cost: 1200,
    tags: ['poke', 'setup'],
    accent: '#a78bfa',
    icon: 'spark',
  },
  {
    id: 'chain-battery',
    name: 'Chain Battery',
    category: 'Spirit',
    tier: 'TIER 2',
    cost: 2100,
    tags: ['tempo', 'rotate'],
    accent: '#facc15',
    icon: 'gear',
  },
  {
    id: 'morrow-spike',
    name: 'Morrow Spike',
    category: 'Spirit',
    tier: 'TIER 2',
    cost: 2600,
    tags: ['control', 'combo'],
    accent: '#c084fc',
    icon: 'pulse',
  },
  {
    id: 'echo-capacitor',
    name: 'Echo Capacitor',
    category: 'Spirit',
    tier: 'TIER 3',
    cost: 4200,
    tags: ['spell amp', 'combo'],
    accent: '#22d3ee',
    icon: 'spark',
  },
  {
    id: 'rift-shield',
    name: 'Rift Shield',
    category: 'Vitality',
    tier: 'TIER 1',
    cost: 1000,
    tags: ['sustain', 'shield'],
    accent: '#38bdf8',
    icon: 'shield',
  },
  {
    id: 'phase-lattice',
    name: 'Phase Lattice',
    category: 'Vitality',
    tier: 'TIER 2',
    cost: 1800,
    tags: ['regen', 'escape'],
    accent: '#34d399',
    icon: 'shield',
  },
  {
    id: 'hexbreaker-rig',
    name: 'Hexbreaker Rig',
    category: 'Vitality',
    tier: 'TIER 3',
    cost: 3900,
    tags: ['cleanse', 'clutch'],
    accent: '#14b8a6',
    icon: 'hex',
  },
  {
    id: 'bulwark-mesh',
    name: 'Bulwark Mesh',
    category: 'Vitality',
    tier: 'TIER 3',
    cost: 3600,
    tags: ['frontline', 'resist'],
    accent: '#60a5fa',
    icon: 'shield',
  },
]
